highlighter: pygments
permalink: /:year/:month/:day/:title
title: Unibz Redesign Timeline
baseurl: /timeline
url: http://unibz.github.io/timeline/
linked_posts: true

prose:
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
